"""Postgres connection pool and the migration runner.

Deliberately the same hand-rolled design as every Go service's
internal/db/db.go: read migrations/*.sql in filename order, skip ones
already recorded in schema_migrations, apply each in its own transaction.
Using the identical pattern here (instead of Alembic, the standard Python
choice) is a deliberate consistency call — one mental model for "how a
migration runs" across every service in this project regardless of
language, rather than "boring Go tool" + "boring Python tool" that happen to
work differently. Alembic is the right call the day this service's schema
needs anything Alembic does that this doesn't — autogenerated migrations
from ORM model diffs, or down-migrations.
"""

from __future__ import annotations

from pathlib import Path

from psycopg_pool import ConnectionPool

MIGRATIONS_DIR = Path(__file__).parent.parent / "migrations"


def new_pool(database_url: str) -> ConnectionPool:
    pool = ConnectionPool(database_url, min_size=1, max_size=5, open=True)
    pool.wait(timeout=10)
    return pool


def migrate(pool: ConnectionPool) -> None:
    with pool.connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                filename    TEXT PRIMARY KEY,
                applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        conn.commit()

        applied = {
            row[0] for row in conn.execute("SELECT filename FROM schema_migrations").fetchall()
        }

        for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
            if path.name in applied:
                continue
            sql = path.read_text(encoding="utf-8")
            with conn.transaction():
                conn.execute(sql)  # type: ignore[arg-type]
                conn.execute("INSERT INTO schema_migrations (filename) VALUES (%s)", (path.name,))
